# Generated by Django 4.1 on 2022-09-06 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=350)),
                ('email', models.CharField(default='default@email.com', max_length=150, unique=True)),
                ('password', models.CharField(default='admin123456', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350)),
                ('valor_energetico', models.FloatField(default=0, max_length=100)),
                ('carboidratos', models.FloatField(default=0, max_length=100)),
                ('proteinas', models.FloatField(default=0, max_length=100)),
                ('gorduras', models.FloatField(default=0, max_length=100)),
                ('fibra_alimentar', models.FloatField(default=0, max_length=100)),
                ('sodio', models.FloatField(default=0, max_length=100)),
                ('acucares', models.FloatField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=3)),
                ('quantidade', models.IntegerField(blank=True, default=0, max_length=2, null=True)),
                ('garcon_responsavel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.garcon')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=1000)),
                ('pratos', models.TextField()),
                ('garcon', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webpage.garcon')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350)),
                ('foto', models.ImageField(upload_to='Images')),
                ('preco', models.FloatField(default=100.0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='prato_has_ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=3)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.ingrediente')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.prato')),
            ],
        ),
        migrations.AddField(
            model_name='prato',
            name='ingredientes',
            field=models.ManyToManyField(through='webpage.prato_has_ingrediente', to='webpage.ingrediente'),
        ),
        migrations.CreateModel(
            name='pedido_has_prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, max_length=3)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.pedido')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.prato')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='prato',
            field=models.ManyToManyField(through='webpage.pedido_has_prato', to='webpage.prato'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=3)),
                ('validade', models.DateField(default=datetime.datetime(2022, 9, 6, 8, 22, 15, 148322))),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.ingrediente')),
            ],
        ),
    ]
