# Generated by Django 4.1 on 2022-09-06 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=1000)),
                ('pratos', models.TextField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350)),
                ('foto', models.ImageField(upload_to='Assets/Images')),
            ],
        ),
        migrations.RemoveField(
            model_name='garcon',
            name='restaurante_empregador',
        ),
        migrations.AddField(
            model_name='garcon',
            name='email',
            field=models.CharField(default='default@email.com', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='garcon',
            name='password',
            field=models.CharField(default='admin123456', max_length=150),
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
        migrations.AddField(
            model_name='mesa',
            name='garcon_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.garcon'),
        ),
    ]
