# Generated by Django 4.1 on 2022-09-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_mesa_pedido_prato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='preco',
            field=models.FloatField(default=100.0, max_length=100),
        ),
    ]
