# Generated by Django 4.1 on 2022-09-06 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_alter_estoque_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='validade',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 13, 55, 29, 758442)),
        ),
    ]
