# Generated by Django 4.1 on 2022-09-07 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_estoque_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('1', 'Pedido'), ('2', 'Fazendo'), ('3', 'Pronto')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='prato',
            name='tipo',
            field=models.CharField(choices=[('1', 'Entrada'), ('2', 'Executivo'), ('3', 'Carne'), ('4', 'Peixe'), ('5', 'Frango'), ('6', 'Vegano/Vegetariano'), ('7', 'Bebidas'), ('8', 'Sobremesa')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='validade',
            field=models.DateField(default=datetime.datetime(2022, 9, 7, 16, 17, 31, 682413)),
        ),
    ]
