# Generated by Django 4.1 on 2022-09-07 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_pedido_status_prato_tipo_alter_estoque_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='validade',
            field=models.DateField(default=datetime.datetime(2022, 9, 7, 16, 38, 15, 526899)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pedido', 'Pedido'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], default='Pedido', max_length=100),
        ),
        migrations.AlterField(
            model_name='prato',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Executivo', 'Executivo'), ('Carne', 'Carne'), ('Peixe', 'Peixe'), ('Frango', 'Frango'), ('Massa', 'Massa'), ('Vegano/Vegetariano', 'Vegano/Vegetariano'), ('Bebidas', 'Bebidas'), ('Sobremesa', 'Sobremesa')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='prato_has_ingrediente',
            name='quantidade',
            field=models.FloatField(max_length=3),
        ),
    ]
