# Generated by Django 4.1 on 2022-09-15 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_alter_estoque_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='validade',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 16, 47, 51, 342163)),
        ),
    ]
