# Generated by Django 4.1 on 2022-09-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_garcon_user_id_alter_estoque_validade'),
        ('webpage', '0014_alter_estoque_validade'),
    ]

    operations = [
    ]
