# Generated by Django 4.1 on 2022-09-17 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_merge_20220917_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garcon',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='estoque',
            name='validade',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 18, 49, 10, 551153)),
        ),
    ]
