# Generated by Django 4.1 on 2022-09-19 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0016_remove_garcon_user_id_alter_estoque_validade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="validade",
            field=models.DateField(
                default=datetime.datetime(2022, 9, 18, 22, 29, 14, 607906)
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="mesa",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="webpage.mesa",
            ),
        ),
    ]
